---
name: "Build Smart Contract"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npx hardhat compile
