---
name: "Build Smart Contract"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  Checkout:
    name: Checkout
    runs-on: ubuntu-latest
    uses: learn-hackathon-dapps/node-workflow-template/.github/workflows/action.yaml@master
    steps:
      # checkout the repository
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
