---
name: "Build Smart Contract"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  Build:
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
    uses: learn-hackathon-dapps/node-workflow-template/.github/workflows/action.yaml@master
