---
name: "Build Smart Contract"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Compile
        uses: learn-hackathon-dapps/node-workflow-template/.github/workflow/action.yaml@master
